Simicart/siminia-public

src/override/routes.js
src/simi/App/core/ProductFullDetail/Pdetailsbrand/index.js
src/simi/App/core/ProductFullDetail/Pdetailsbrand/pdetailsbrand.module.css
src/simi/App/core/ProductFullDetail/productFullDetail.js
src/simi/App/core/ProductFullDetail/productFullDetail.module.css
src/simi/App/core/RootComponents/Product/productDetailFragment.gql.js
src/simi/App/core/ShopByBrand/components/branddetails/Gallery/gallery.js
src/simi/App/core/ShopByBrand/components/branddetails/Gallery/gallery.module.css
src/simi/App/core/ShopByBrand/components/branddetails/Gallery/index.js
src/simi/App/core/ShopByBrand/components/branddetails/Gallery/item.js
src/simi/App/core/ShopByBrand/components/branddetails/Gallery/item.module.css
src/simi/App/core/ShopByBrand/components/branddetails/bdetailscategories.js
src/simi/App/core/ShopByBrand/components/branddetails/branddetails.module.css
src/simi/App/core/ShopByBrand/components/branddetails/index.js
src/simi/App/core/ShopByBrand/components/branddetails/products/index.js
src/simi/App/core/ShopByBrand/components/branddetails/products/productsContent.js
src/simi/App/core/ShopByBrand/components/branddetails/products/productsContent.module.css
src/simi/App/core/ShopByBrand/components/brands/brands.js
src/simi/App/core/ShopByBrand/components/category/index.js
src/simi/App/core/ShopByBrand/queries/filterIntrospectionQuery.graphql
src/simi/App/core/ShopByBrand/talons/useBrandCategory.js
src/simi/App/core/ShopByBrand/talons/useBrandDetails.js
src/simi/App/core/ShopByBrand/talons/useProductsContent.js

Add brand details, category, product details brand

12.0/feature-rich/ShopByBrand

---

src/simi/App/core/Checkout/checkoutPage.js
src/simi/App/core/ProductFullDetail/ProductLabel/index.js
src/simi/App/core/ProductFullDetail/ProductLabel/productLabel.gql.js
src/simi/App/core/ProductFullDetail/ProductLabel/styles.scss
src/simi/App/core/ProductImageCarousel/carousel.js
src/simi/BaseComponents/GridItem/item.js
src/simi/queries/catalog_gql/catalogFragment.gql.js
src/simi/queries/catalog_gql/category.gql.js

update product label 11-1

---

src/simi/BaseComponents/Breadcrumbs/breadcrumbs.module.css

fix breadcrumbs

---

src/simi/App/core/ProductImageCarousel/carousel.js
src/simi/App/core/ShopByBrand/components/branddetails/products/productsContent.js
src/simi/App/core/ShopByBrand/talons/useProductsContent.js

12.0/feature rich/product label1

---

src/simi/App/core/ProductFullDetail/Pdetailsbrand/index.js
src/simi/App/core/ShopByBrand/queries/getBrandProducts.graphql
src/simi/App/core/ShopByBrand/talons/useBrandInfo.js
src/simi/BaseComponents/Products/Gallery/gallery.js

fix brand for product detail

---

src/simi/App/core/Cart/PriceAdjustments/priceAdjustments.js
src/simi/App/core/Cart/PriceAdjustments/priceAdjustments.module.css

Fix Reward Point Cart and Checkout

---

src/simi/BaseComponents/GridItem/item.js
src/simi/BaseComponents/GridItem/item.module.css

Update narrow screen fix for product listing
- [ x] Bugfix

Fix narrow mobile screen

---

src/simi/BaseComponents/Products/Filter/filter.scss
src/simi/BaseComponents/Products/Filter/index.js
src/simi/BaseComponents/Products/index.js

exclude current category from filter options
- [x ] Bugfix

exclude current category from filter options

---

src/override/routes.js
src/simi/App/core/ContactPage/contactLink.js
src/simi/App/core/ContactPage/contactPage.js
src/simi/App/core/ContactPage/contactPage.module.css
src/simi/App/core/ContactPage/contactPage.shimmer.js
src/simi/App/core/ContactPage/contactPage.shimmer.module.css
src/simi/App/core/ContactPage/index.js
src/simi/talons/ContactPage/contactUs.gql.js
src/simi/talons/ContactPage/index.js
src/simi/talons/ContactPage/useContactLink.js
src/simi/talons/ContactPage/useContactPage.js

add contact page

---

src/override/routes.js
src/simi/App/core/CommunicationsPage/communicationsPage.js
src/simi/App/core/CommunicationsPage/communicationsPage.module.css
src/simi/App/core/CommunicationsPage/index.js

add communications page

---

src/simi/BaseComponents/Products/Filter/index.js
src/simi/queries/catalog_gql/category.gql.js
src/simi/queries/catalog_gql/simiCategory.gql.js

Issue Number: 56
Server is returning category options that's not right.
So client will => Only show child cate options on filter.

Fix Filter only show child Cate

---

src/simi/App/core/Checkout/DeliveryDateTime/deliveryDateTime.js
src/simi/App/core/Checkout/DeliveryDateTime/style.scss
src/simi/App/core/Checkout/checkoutPage.js

update delivery time

---

src/simi/App/core/Cart/PriceAdjustments/priceAdjustments.js
src/simi/App/core/Cart/PriceAdjustments/priceAdjustments.module.css
src/simi/App/core/Cart/PriceSummary/priceSummary.js
src/simi/App/core/MiniCart/miniCart.js
src/simi/App/core/MiniCart/miniCartFragments.gql.js
src/simi/talons/Cart/priceSummaryFragments.gql.js
src/simi/talons/Cart/usePriceSummary.js
src/simi/talons/MiniCart/useMiniCart.js

Fix reward point 2

---

src/simi/App/core/LeftMenu/leftMenu.js

Fix Left Menu

---

src/simi/App/core/ShopByBrand/components/category/index.js

add meta title,keywords, description

---

src/simi/App/core/MiniCart/miniCartFragments.gql.js
src/simi/talons/Cart/priceSummaryFragments.gql.js

Fix Reward Point Api

---

src/simi/App/core/Seo/Canonical.js
src/simi/App/core/Seo/HomeTitle.js
src/simi/App/core/Seo/Markup/Category.js
src/simi/App/core/Seo/Markup/Page.js
src/simi/App/core/Seo/Markup/Product.js
src/simi/App/core/Seo/Markup/RsHome.js
src/simi/App/core/Seo/Markup/RsSeller.js
src/simi/App/core/Seo/Robots.js
src/simi/App/core/Seo/talons/useStoreConfigData.js

fix bug store config data

---

src/simi/App/core/OrderHistoryPage/orderHistoryPage.js
src/simi/App/core/OrderHistoryPage/orderHistoryPage.module.css
src/simi/App/core/OrderHistoryPage/orderHistoryPageMb.js
src/simi/App/core/OrderHistoryPage/orderRow.js
src/simi/talons/OrderHistory/orderHistoryPage.gql.js
src/simi/talons/OrderHistory/useOrderHistoryPage.js

update pagination on orderhistory page

---

src/override/routes.js
src/simi/App/core/AddressBookPage/addressBookPage.js
src/simi/App/core/AddressBookPage/addressBookPage.module.css
src/simi/App/core/SavedPaymentsPage/index.js
src/simi/App/core/SavedPaymentsPage/savedPaymentsPage.js
src/simi/App/core/SavedPaymentsPage/savedPaymentsPage.module.css

add left menu for savedPayment & style address book

---

src/simi/App/core/ProductFullDetail/productFullDetail.js
src/simi/App/core/RootComponents/Product/productDetailFragment.gql.js
src/simi/App/core/Seo/Markup/Product.js

add DataStructure for productFullDetail

---

src/simi/App/core/RootComponents/Product/productDetailFragment.gql.js
src/simi/App/core/Seo/Canonical.js
src/simi/App/core/Seo/Markup/Category.js
src/simi/App/core/Seo/Markup/Page.js
src/simi/App/core/Seo/Markup/Product.js
src/simi/App/core/Seo/Markup/RsHome.js
src/simi/App/core/Seo/Markup/RsSeller.js
src/simi/App/core/Seo/Robots.js
src/simi/App/core/Seo/talons/useStoreConfigData.js

12.0/feature rich/mageworx seo

---

src/simi/App/core/Main/main.js
src/simi/App/core/ProductFullDetail/productFullDetail.js
src/simi/App/core/ProductFullDetail/productbuilderFullDetail.js
src/simi/App/core/RootComponents/Category/category.js
src/simi/App/core/RootComponents/Product/productDetailFragment.gql.js
src/simi/App/core/SeoBasic/Canonical.js
src/simi/App/core/SeoBasic/Markup/Category.js
src/simi/App/core/SeoBasic/Markup/Page.js
src/simi/App/core/SeoBasic/Markup/Product.js
src/simi/App/core/SeoBasic/Markup/RsHome.js
src/simi/App/core/SeoBasic/Robots.js
src/simi/App/core/SeoBasic/index.js

add seo basic

---

src/simi/App/core/Main/main.js
src/simi/App/core/ProductFullDetail/ProductReview/index.js
src/simi/App/core/ProductFullDetail/productFullDetail.js
src/simi/App/core/ProductFullDetail/productbuilderFullDetail.js
src/simi/App/core/RootComponents/CMS/cms.js
src/simi/App/core/RootComponents/Category/category.js
src/simi/App/core/Seo/Markup/Product.js
src/simi/App/core/Seo/index.js
src/simi/App/core/SeoBasic/CanonicalBasic.js
src/simi/App/core/SeoBasic/Markup/Product.js
src/simi/App/core/SeoBasic/RobotsBasic.js
src/simi/App/core/SeoBasic/index.js

check mageworx enable

---

src/simi/App/core/OrderDetailPage/orderDetailPage.gql.js
src/simi/App/core/OrderDetailPage/orderDetailPage.js
src/simi/App/core/OrderDetailPage/orderDetailPage.module.scss

Add reward points to order detail

---

src/simi/App/core/Header/header.module.css

Fix warp when menu very long

---

src/simi/talons/ProductFullDetail/getDisplayPrice.js

* Use minimumPrice as base price instead of regularPrice
* SimpleProduct not showing discount on Product Detail Page
Issue Number: https://github.com/Simicart/siminia-public/issues/72
* Use price with discount for price calculation

Fix SimpleProduct not having discount

---

src/simi/App/core/Cart/PriceAdjustments/priceAdjustments.js
src/simi/App/core/OrderDetailPage/orderDetailPage.js
src/simi/talons/Cart/usePriceSummary.js

Fix rewardPoint slider

---

src/simi/App/nativeInner/GridItem/Price/Bundle.js
src/simi/App/nativeInner/GridItem/Price/Grouped.js
src/simi/App/nativeInner/GridItem/Price/Simple.js
src/simi/App/nativeInner/GridItem/Price/index.js
src/simi/App/nativeInner/GridItem/Price/price.scss
src/simi/App/nativeInner/GridItem/index.js
src/simi/App/nativeInner/GridItem/item.js
src/simi/App/nativeInner/GridItem/item.module.css
src/simi/App/nativeInner/NoMatch/index.js
src/simi/App/nativeInner/Products/Filter/RangeSlider.js
src/simi/App/nativeInner/Products/Filter/filter.scss
src/simi/App/nativeInner/Products/Filter/index.js
src/simi/App/nativeInner/Products/Filter/rangeslider.scss
src/simi/App/nativeInner/Products/Gallery/gallery.js
src/simi/App/nativeInner/Products/Gallery/gallery.scss
src/simi/App/nativeInner/Products/Gallery/index.js
src/simi/App/nativeInner/Products/NoProductsFound/index.js
src/simi/App/nativeInner/Products/NoProductsFound/noProductsFound.js
src/simi/App/nativeInner/Products/NoProductsFound/noProductsFound.module.css
src/simi/App/nativeInner/Products/Sortby/index.js
src/simi/App/nativeInner/Products/SortbyPrice/index.js
src/simi/App/nativeInner/Products/index.js
src/simi/App/nativeInner/Products/loadMore.js
src/simi/App/nativeInner/Products/products.scss
src/simi/App/nativeInner/RootComponents/Category/category.js
src/simi/App/nativeInner/RootComponents/Category/category.module.css
src/simi/App/nativeInner/RootComponents/Category/categoryContent.shimmer.js
src/simi/App/nativeInner/RootComponents/Category/categoryHeader.js
src/simi/App/nativeInner/RootComponents/Category/index.js

add products listing - native

---

src/simi/App/core/Cart/PriceAdjustments/priceAdjustments.js

Fix reward point bug in cart and checkout

---

src/simi/App/core/Checkout/DeliveryDateTime/deliveryDateTime.js
src/simi/App/core/Checkout/checkoutPage.js
src/simi/App/core/Checkout/checkoutPage.scss

add checkbox delivery time

---

src/simi/App/nativeInner/ProductFullDetail/SizeChart/index.js
src/simi/App/nativeInner/ProductFullDetail/addToCartPopup.js
src/simi/App/nativeInner/ProductFullDetail/productFullDetail.js
src/simi/App/nativeInner/ProductFullDetail/productFullDetail.scss
src/simi/App/nativeInner/ProductFullDetail/statusBar.scss

fix product detail - native

---

src/simi/App/core/Checkout/DeliveryDateTime/deliveryDateTime.js
src/simi/App/core/Checkout/checkoutPage.js
src/simi/App/core/Checkout/checkoutPage.module.css
src/simi/BaseComponents/ButtonLoader/buttonLoader.js
src/simi/BaseComponents/ButtonLoader/buttonLoader.module.css
src/simi/BaseComponents/ButtonLoader/index.js

Button Loader Component

---

src/simi/App/core/Seo/Canonical.js
src/simi/App/nativeInner/BaseComponents/Dropdownoption/index.js
src/simi/App/nativeInner/BaseComponents/Dropdownoption/index.scss
src/simi/App/nativeInner/GridItem/item.js
src/simi/App/nativeInner/GridItem/item.module.css
src/simi/App/nativeInner/Products/Filter/index.js
src/simi/App/nativeInner/Products/Sortby/index.js
src/simi/App/nativeInner/Products/Sortby/sortby.scss
src/simi/App/nativeInner/Products/SortbyPrice/index.js
src/simi/App/nativeInner/Products/index.js
src/simi/App/nativeInner/Products/products.scss

12.0/native inner/products listing

---

src/simi/App/core/Cart/ProductListing/product.module.css
src/simi/App/nativeInner/Cart/BottomNotification/BottomNotification.js
src/simi/App/nativeInner/Cart/CartProduct/CartProduct.js
src/simi/App/nativeInner/Cart/CartProduct/CartProduct.module.css
src/simi/App/nativeInner/Cart/ConfirmPopup/confirmPopup.js
src/simi/App/nativeInner/Cart/ConfirmPopup/confirmPopup.module.css
src/simi/App/nativeInner/Cart/CouponCode/couponCode.js
src/simi/App/nativeInner/Cart/CouponCode/couponCode.module.css
src/simi/App/nativeInner/Cart/PriceAdjustments/priceAdjustments.js
src/simi/App/nativeInner/Cart/PriceAdjustments/priceAdjustments.module.css
src/simi/App/nativeInner/Cart/PriceSummary/priceSummary.js
src/simi/App/nativeInner/Cart/PriceSummary/priceSummary.module.css
src/simi/App/nativeInner/Cart/PriceWithColor/PriceWithColor.js
src/simi/App/nativeInner/Cart/PriceWithColor/index.js
src/simi/App/nativeInner/Cart/ProductListingWithBrandSeparation/ProductListingWithBrandSeparation.config.js
src/simi/App/nativeInner/Cart/ProductListingWithBrandSeparation/ProductListingWithBrandSeparation.js
src/simi/App/nativeInner/Cart/ProductListingWithBrandSeparation/ProductListingWithBrandSeparation.module.css
src/simi/App/nativeInner/Cart/Quantity/quantity.js
src/simi/App/nativeInner/Cart/Quantity/quantity.module.css
src/simi/App/nativeInner/Cart/RectButton/RectButton.js
src/simi/App/nativeInner/Cart/RectButton/RectOutlineButton.js
src/simi/App/nativeInner/Cart/RedButton/RedButton.js
src/simi/App/nativeInner/Cart/bottomNotificationHook/useBottomNotification.js
src/simi/App/nativeInner/Cart/cartPage.js
src/simi/App/nativeInner/Cart/cartPage.module.css

12.0/native inner/feature/cart

---

src/simi/App/nativeInner/ProductFullDetail/AlertMessages/alertMessages.js
src/simi/App/nativeInner/ProductFullDetail/AlertMessages/index.js
src/simi/App/nativeInner/ProductFullDetail/AlertMessages/styles.scss
src/simi/App/nativeInner/ProductFullDetail/SizeChart/index.js
src/simi/App/nativeInner/ProductFullDetail/SizeChart/style.scss
src/simi/App/nativeInner/ProductFullDetail/addToCartPopup.js
src/simi/App/nativeInner/ProductFullDetail/productFullDetail.js
src/simi/App/nativeInner/ProductFullDetail/productFullDetail.module.css
src/simi/App/nativeInner/ProductFullDetail/productFullDetail.scss
src/simi/App/nativeInner/ProductFullDetail/statusBar.scss
src/simi/App/nativeInner/talons/useProductFullDetail.js

update product detail - native & toast component

---

src/simi/App/core/Seo/Canonical.js
src/simi/App/core/Seo/Markup/Product.js

fix bug SEO, update AggregateRating

---

src/simi/App/nativeInner/BaseComponents/Dropdownoption/index.js
src/simi/App/nativeInner/BaseComponents/Dropdownoption/index.scss
src/simi/App/nativeInner/GridItem/item.js
src/simi/App/nativeInner/GridItem/item.module.css
src/simi/App/nativeInner/Header/header.module.css
src/simi/App/nativeInner/Main/main.module.css
src/simi/App/nativeInner/Products/Filter/filter.scss
src/simi/App/nativeInner/Products/Gallery/gallery.scss
src/simi/App/nativeInner/Products/Sortby/index.js
src/simi/App/nativeInner/Products/Sortby/sortby.scss
src/simi/App/nativeInner/Products/SortbyPrice/index.js
src/simi/App/nativeInner/Products/SortbyPrice/sortbyPrice.scss
src/simi/App/nativeInner/Products/index.js
src/simi/App/nativeInner/Products/products.scss
src/simi/App/nativeInner/RootComponents/Category/category.js

update sort by price

---

src/simi/App/nativeInner/Header/Component/SearchForm.js
src/simi/App/nativeInner/Header/Component/search.scss
src/simi/App/nativeInner/Header/Component/searchAutoComplete/searchAutoComplete.module.css
src/simi/App/nativeInner/Header/header.js
src/simi/App/nativeInner/Header/header.module.css
src/simi/App/nativeInner/Main/main.js

update new header && add footer(desktop site)

---

src/simi/App/nativeInner/ProductFullDetail/ProductReview/productReview.scss
src/simi/App/nativeInner/ProductFullDetail/productFullDetail.js

update padding review - native

---

src/simi/App/core/ProductFullDetail/productbuilderFullDetail.js

update rating value

---

src/simi/App/nativeInner/ProductFullDetail/AlertMessages/styles.scss
src/simi/App/nativeInner/ProductFullDetail/ProductReview/productReview.scss
src/simi/App/nativeInner/ProductFullDetail/addToCartPopup.js
src/simi/App/nativeInner/ProductFullDetail/productFullDetail.js
src/simi/App/nativeInner/ProductFullDetail/productFullDetail.scss
src/simi/App/nativeInner/ProductFullDetail/statusBar.scss
src/simi/App/nativeInner/ProductImageCarousel/ImageLightbox.js
src/simi/App/nativeInner/ProductImageCarousel/ImageLightbox.scss
src/simi/App/nativeInner/ProductImageCarousel/carousel.js
src/simi/App/nativeInner/ProductImageCarousel/carousel.shimmer.js
src/simi/App/nativeInner/ProductImageCarousel/carousel.shimmer.module.css
src/simi/App/nativeInner/ProductImageCarousel/imageLoading/index.js
src/simi/App/nativeInner/ProductImageCarousel/imageLoading/styles.scss
src/simi/App/nativeInner/ProductImageCarousel/index.js
src/simi/App/nativeInner/ProductImageCarousel/style.css

update product details - native

---

src/simi/App/nativeInner/Header/Component/SearchForm.js
src/simi/App/nativeInner/Header/Component/search.scss
src/simi/App/nativeInner/Header/Component/searchAutoComplete/searchAutoComplete.module.css
src/simi/App/nativeInner/Header/header.module.css

update search on header - native

---

src/simi/App/nativeInner/CategoryList/categoryList.js
src/simi/App/nativeInner/CategoryList/categoryList.module.css
src/simi/App/nativeInner/CategoryList/categoryTile.js
src/simi/App/nativeInner/CategoryList/categoryTile.module.css
src/simi/App/nativeInner/CategoryList/index.js
src/simi/App/nativeInner/NoMatch/index.js
src/simi/App/nativeInner/Products/SortbyPrice/index.js
src/simi/App/nativeInner/Products/SortbyPrice/sortbyPrice.scss
src/simi/App/nativeInner/Products/index.js
src/simi/App/nativeInner/Products/products.scss
src/simi/App/nativeInner/RootComponents/CMS/cms.js
src/simi/App/nativeInner/RootComponents/CMS/cms.module.css
src/simi/App/nativeInner/RootComponents/CMS/index.js

update sort, add category list - native

---

src/simi/App/nativeInner/FooterNative/footerNative.js
src/simi/App/nativeInner/FooterNative/footerNative.module.css
src/simi/App/nativeInner/Header/Component/SearchForm.js
src/simi/App/nativeInner/Header/Component/search.scss
src/simi/App/nativeInner/Header/header.js

update header-footer - native (+ back button on header , + padding on footer)

---

src/index.css
src/simi/App/nativeInner/CategoryList/categoryList.js
src/simi/App/nativeInner/CategoryList/productsList.js
src/simi/App/nativeInner/CategoryList/productsList.module.css
src/simi/App/nativeInner/Products/products.scss
src/simi/App/nativeInner/talons/CategoryList/categoryList.gql.js
template.html

Add sub categories

---

src/simi/App/core/PriceWrapper/CrossedOutPrice/CrossedOutPrice.js
src/simi/App/core/PriceWrapper/CrossedOutPrice/CrossedOutPrice.module.css
src/simi/App/core/PriceWrapper/CrossedOutPrice/index.js
src/simi/App/core/PriceWrapper/Price.js
src/simi/App/core/ProductFullDetail/productFullDetail.js
src/simi/App/core/ProductFullDetail/productbuilderFullDetail.js
src/simi/talons/ProductFullDetail/getDisplayPrice.js

* Product detail page only shows 1 price
* Now also shows original price if the product is discounted

fix: show original price before discount price in product detail

---

src/simi/BaseComponents/GridItem/item.js
src/simi/BaseComponents/GridItem/item.module.css

fix discount label

---

src/simi/App/nativeInner/ProductFullDetail/productFullDetail.js
src/simi/App/nativeInner/ProductFullDetail/productFullDetail.module.css
src/simi/App/nativeInner/ProductFullDetail/productFullDetail.scss

update short description

---

src/simi/App/nativeInner/Header/Component/SearchForm.js
src/simi/App/nativeInner/Header/Component/search.scss
src/simi/App/nativeInner/Header/header.js
src/simi/App/nativeInner/Header/header.module.css

update header on cart page, login page

---

src/simi/App/nativeInner/FooterNative/footerNative.js

fix bottom menu

---

src/simi/App/nativeInner/CategoryList/categoryList.js
src/simi/App/nativeInner/Products/Sortby/index.js
src/simi/App/nativeInner/Products/Sortby/sortby.scss
src/simi/App/nativeInner/Products/index.js
src/simi/App/nativeInner/Products/products.scss

Update sortby, filter

---

src/override/routesNative.js
src/simi/App/nativeInner/OrderHistoryPage/index.js
src/simi/App/nativeInner/OrderHistoryPage/orderHistoryPage.js
src/simi/App/nativeInner/OrderHistoryPage/orderHistoryPage.module.css
src/simi/App/nativeInner/OrderHistoryPage/orderHistoryPageMb.js
src/simi/App/nativeInner/OrderHistoryPage/orderHistoryPageMb.module.scss
src/simi/App/nativeInner/OrderHistoryPage/orderRow.js
src/simi/App/nativeInner/OrderHistoryPage/orderRow.module.css
src/simi/App/nativeInner/OrderHistoryPage/orderRowCustom.js
src/simi/App/nativeInner/OrderHistoryPage/useOrderRow.js

add new my orders page - native

---

src/simi/App/nativeInner/Header/Component/SearchForm.js
src/simi/App/nativeInner/Header/header.js

update header on my profile - native

---

src/override/routesNative.js
src/simi/App/nativeInner/WishlistPage/index.js
src/simi/App/nativeInner/WishlistPage/useWishListPage.js
src/simi/App/nativeInner/WishlistPage/wishlist.js
src/simi/App/nativeInner/WishlistPage/wishlist.module.css
src/simi/App/nativeInner/WishlistPage/wishlistItem.js
src/simi/App/nativeInner/WishlistPage/wishlistItem.module.css
src/simi/App/nativeInner/WishlistPage/wishlistItems.js
src/simi/App/nativeInner/WishlistPage/wishlistItems.module.css
src/simi/App/nativeInner/WishlistPage/wishlistPage.js
src/simi/App/nativeInner/WishlistPage/wishlistPage.module.css
src/simi/App/nativeInner/talons/WishlistPage/createWishlist.gql.js
src/simi/App/nativeInner/talons/WishlistPage/useActionMenu.js
src/simi/App/nativeInner/talons/WishlistPage/useCreateWishlist.js
src/simi/App/nativeInner/talons/WishlistPage/useWishlist.js
src/simi/App/nativeInner/talons/WishlistPage/useWishlistItem.js
src/simi/App/nativeInner/talons/WishlistPage/useWishlistItems.js
src/simi/App/nativeInner/talons/WishlistPage/useWishlistPage.js
src/simi/App/nativeInner/talons/WishlistPage/wishlist.gql.js
src/simi/App/nativeInner/talons/WishlistPage/wishlistConfig.gql.ce.js
src/simi/App/nativeInner/talons/WishlistPage/wishlistConfig.gql.ee.js
src/simi/App/nativeInner/talons/WishlistPage/wishlistFragment.gql.ee.js
src/simi/App/nativeInner/talons/WishlistPage/wishlistFragment.gql.js
src/simi/App/nativeInner/talons/WishlistPage/wishlistItem.gql.js
src/simi/App/nativeInner/talons/WishlistPage/wishlistItemFragments.gql.js
src/simi/App/nativeInner/talons/WishlistPage/wishlistPage.gql.js

add wish list page - native

---

src/override/routesNative.js
src/simi/App/nativeInner/AccountInformationPage/accountInformationPage.js
src/simi/App/nativeInner/AccountInformationPage/accountInformationPage.module.css
src/simi/App/nativeInner/AccountInformationPage/index.js

Add profile page - native

---

src/simi/App/nativeInner/FooterNative/footerNative.js
src/simi/App/nativeInner/Header/Component/SearchForm.js
src/simi/App/nativeInner/Header/header.js

update header & bottom menu on order details page

---

src/simi/App/nativeInner/OrderDetailPage/orderDetailPage.js
src/simi/App/nativeInner/OrderDetailPage/orderDetailPage.module.scss

add product image for order detail - native

---

src/simi/App/nativeInner/FooterNative/footerNative.js
src/simi/App/nativeInner/Header/Component/SearchForm.js
src/simi/App/nativeInner/Loader/index.js
src/simi/App/nativeInner/Loader/styles.scss
src/simi/App/nativeInner/OrderDetailPage/orderDetailPage.js
src/simi/App/nativeInner/OrderHistoryPage/orderHistoryPageMb.js
src/simi/App/nativeInner/ProductFullDetail/addToCartPopup.js
src/simi/App/nativeInner/ProductFullDetail/statusBar.scss
src/simi/App/nativeInner/ProductImageCarousel/carousel.js
src/simi/App/nativeInner/ProductImageCarousel/imageLoading/index.js
src/simi/App/nativeInner/ProductImageCarousel/imageLoading/styles.scss
src/simi/talons/OrderHistory/useOrderHistoryPage.js

update Loader & fixbug

---

src/simi/App/core/Cart/PriceSummary/priceSummary.module.css
src/simi/App/nativeInner/AccountInformationPage/accountInformationPage.js
src/simi/App/nativeInner/AccountInformationPage/validators.js
src/simi/App/nativeInner/Cart/CartProduct/CartProduct.module.css
src/simi/App/nativeInner/Cart/PriceSummary/priceSummary.module.css
src/simi/App/nativeInner/CategoryList/productsList.module.css

Add validators, update cart page

---

src/override/routesNative.js
src/simi/App/nativeInner/ProductReviewPage/ReviewItems/index.js
src/simi/App/nativeInner/ProductReviewPage/ReviewItems/reviewItem.js
src/simi/App/nativeInner/ProductReviewPage/ReviewItems/reviewItem.module.css
src/simi/App/nativeInner/ProductReviewPage/ReviewItems/reviewItemMb.js
src/simi/App/nativeInner/ProductReviewPage/ReviewItems/reviewItemMb.module.css
src/simi/App/nativeInner/ProductReviewPage/index.js
src/simi/App/nativeInner/ProductReviewPage/productReview.gql.js
src/simi/App/nativeInner/ProductReviewPage/productReviewPage.js
src/simi/App/nativeInner/ProductReviewPage/productReviewPage.module.css
src/simi/App/nativeInner/ProductReviewPage/useGetProductReview.js

Add product review page - native

---

src/simi/App/nativeInner/Checkout/GuestSignIn/guestSignIn.js
src/simi/App/nativeInner/Checkout/GuestSignIn/guestSignIn.module.css
src/simi/App/nativeInner/Checkout/GuestSignIn/index.js
src/simi/App/nativeInner/Checkout/ItemsReview/item.js
src/simi/App/nativeInner/Checkout/OrderSummary/PriceSummary/priceSummary.js
src/simi/App/nativeInner/Checkout/checkoutPage.js
src/simi/App/nativeInner/Checkout/checkoutPage.module.css

Style signin and check show grandtotal label in phone  at checkout page

---

src/simi/App/nativeInner/ProductReviewPage/ReviewItems/reviewItemMb.js
src/simi/App/nativeInner/ProductReviewPage/ReviewItems/reviewItemMb.module.css
src/simi/App/nativeInner/ProductReviewPage/productReviewPage.js
src/simi/App/nativeInner/ProductReviewPage/productReviewPage.module.css

Update product review

---

src/simi/App/nativeInner/Cart/PriceAdjustments/ShippingMethods/index.js
src/simi/App/nativeInner/Cart/PriceAdjustments/ShippingMethods/shippingForm.js
src/simi/App/nativeInner/Cart/PriceAdjustments/ShippingMethods/shippingForm.module.css
src/simi/App/nativeInner/Cart/PriceAdjustments/ShippingMethods/shippingMethods.js
src/simi/App/nativeInner/Cart/PriceAdjustments/ShippingMethods/shippingMethods.module.css
src/simi/App/nativeInner/Cart/PriceAdjustments/ShippingMethods/shippingRadio.js
src/simi/App/nativeInner/Cart/PriceAdjustments/ShippingMethods/shippingRadio.module.css
src/simi/App/nativeInner/Cart/PriceAdjustments/ShippingMethods/shippingRadios.js
src/simi/App/nativeInner/Cart/PriceAdjustments/ShippingMethods/shippingRadios.module.css
src/simi/App/nativeInner/Cart/PriceAdjustments/priceAdjustments.js
src/simi/App/nativeInner/Cart/PriceAdjustments/priceAdjustments.module.css
src/simi/App/nativeInner/Cart/PriceSummary/priceSummary.js
src/simi/App/nativeInner/Cart/PriceSummary/priceSummary.module.css
src/simi/App/nativeInner/Cart/cartPage.js
src/simi/App/nativeInner/Cart/cartPage.module.css

update price adjustments and update cart layout

---

src/simi/App/nativeInner/ProductReviewPage/ReviewItems/reviewItem.js
src/simi/App/nativeInner/ProductReviewPage/ReviewItems/reviewItem.module.css
src/simi/App/nativeInner/ProductReviewPage/ReviewItems/reviewItemMb.js
src/simi/App/nativeInner/ProductReviewPage/ReviewItems/reviewItemMb.module.css

Update button view details

---

src/simi/App/nativeInner/Cart/CartProduct/CartProduct.js
src/simi/App/nativeInner/Cart/CartProduct/CartProduct.module.css
src/simi/App/nativeInner/Cart/PriceAdjustments/priceAdjustments.js
src/simi/App/nativeInner/Cart/cartPage.module.css

Cart page: update image style and price summary style

---

src/override/routesNative.js
src/simi/App/nativeInner/RewardPoint/RewardPointDataPage/index.js
src/simi/App/nativeInner/RewardPoint/RewardPointDataPage/rewardPoint.js
src/simi/App/nativeInner/RewardPoint/RewardPointDataPage/rewardPoint.module.css
src/simi/App/nativeInner/RewardPoint/RewardTransactions/index.js
src/simi/App/nativeInner/RewardPoint/RewardTransactions/rewardTransaction.module.css
src/simi/App/nativeInner/RewardPoint/RewardTransactions/rewardTransactions.js

Add reward points - native

---

src/override/routesNative.js
src/simi/App/nativeInner/MyAccountPage/myAccountPage.js
src/simi/App/nativeInner/SavedPaymentsPage/index.js
src/simi/App/nativeInner/SavedPaymentsPage/savedPaymentsPage.js
src/simi/App/nativeInner/SavedPaymentsPage/savedPaymentsPage.module.css

remove help center on my account , add saved payments on my account

---

src/override/routesNative.js
src/simi/App/nativeInner/AccountSubcriptionPage/accountSubcriptionPage.js
src/simi/App/nativeInner/AccountSubcriptionPage/accountSubcriptionPage.module.css
src/simi/App/nativeInner/AccountSubcriptionPage/index.js
src/simi/App/nativeInner/AccountSubcriptionPage/newsletter.gql.js
src/simi/App/nativeInner/Main/main.js
src/simi/App/nativeInner/OrderDetailPage/orderDetailPage.js
src/simi/App/nativeInner/talons/MyAccount/useNewsletter.js

12.0/native inner/account subscriptions

---

src/simi/App/nativeInner/AddressBookPage/addEditDialog.js
src/simi/App/nativeInner/AddressBookPage/addressBookPage.js
src/simi/App/nativeInner/AddressBookPage/addressBookPage.module.css
src/simi/App/nativeInner/AddressBookPage/addressCard.js
src/simi/App/nativeInner/AddressBookPage/addressCard.module.css
src/simi/App/nativeInner/Country/__tests__/__snapshots__/country.spec.js.snap
src/simi/App/nativeInner/Country/__tests__/country.spec.js
src/simi/App/nativeInner/Country/country.gql.js
src/simi/App/nativeInner/Country/country.js
src/simi/App/nativeInner/Country/country.module.css
src/simi/App/nativeInner/Country/index.js
src/simi/App/nativeInner/Main/main.module.css
src/simi/App/nativeInner/Select/index.js
src/simi/App/nativeInner/Select/option.js
src/simi/App/nativeInner/Select/select.js
src/simi/App/nativeInner/Select/select.module.css

update address book

---

src/simi/App/nativeInner/CategoryList/CategoryDescription/categoryDescription.js
src/simi/App/nativeInner/CategoryList/CategoryDescription/categoryDescription.scss
src/simi/App/nativeInner/CategoryList/categoryList.module.css
src/simi/App/nativeInner/GridItem/item.module.css
src/simi/App/nativeInner/Products/index.js
src/simi/App/nativeInner/Products/products.scss
src/simi/App/nativeInner/ShopByBrand/components/branddetails/branddetails.module.css
src/simi/App/nativeInner/ShopByBrand/components/branddetails/index.js

Update categories, shop by brand. search

---

src/simi/App/core/RewardPoint/RewardPointDataPage/rewardPoint.js
src/simi/App/core/RewardPoint/RewardPointDataPage/rewardPoint.module.css
src/simi/App/core/RewardPoint/RewardTransactions/rewardTransaction.module.css
src/simi/App/core/RewardPoint/RewardTransactions/rewardTransactions.js

Update reward point for mobile

---

src/simi/App/nativeInner/Header/header.js

add id for header

---

src/simi/App/nativeInner/RewardPoint/RewardPointDataPage/rewardPoint.js
src/simi/App/nativeInner/RewardPoint/RewardPointDataPage/rewardPoint.module.css
src/simi/App/nativeInner/RewardPoint/RewardTransactions/rewardTransaction.module.css
src/simi/App/nativeInner/RewardPoint/RewardTransactions/rewardTransactions.js

Add reward point for native

---

src/simi/App/nativeInner/AccountInformationPage/accountInformationPage.module.css
src/simi/App/nativeInner/Products/Filter/filter.scss
src/simi/App/nativeInner/Products/index.js
src/simi/App/nativeInner/Products/products.scss
src/simi/App/nativeInner/RootComponents/Search/search.js
src/simi/App/nativeInner/RootComponents/Search/search.module.css
src/simi/App/nativeInner/ShopByBrand/components/branddetails/branddetails.module.css
src/simi/App/nativeInner/ShopByBrand/components/brands/brands.module.css
src/simi/App/nativeInner/WishlistPage/wishlistItem.module.css

Update background shop by brand, fix margin padding categories

---

src/override/button.module.css
src/simi/App/nativeInner/AddressBookPage/addressBookPage.module.css
src/simi/App/nativeInner/Cart/LoadingBridge/LoadingBridge.module.css
src/simi/App/nativeInner/Dialog/dialog.module.css
src/simi/App/nativeInner/FooterNative/footerNative.module.css
src/simi/App/nativeInner/Header/Component/search.scss
src/simi/App/nativeInner/Header/cartCounter.module.css
src/simi/App/nativeInner/Header/cartTrigger.module.css
src/simi/App/nativeInner/Header/header.module.css
src/simi/App/nativeInner/Loader/styles.scss
src/simi/App/nativeInner/MyAccountPage/myAccountPage.module.css
src/simi/App/nativeInner/OrderDetailPage/orderDetailPage.module.scss
src/simi/App/nativeInner/OrderHistoryPage/orderHistoryPage.module.css
src/simi/App/nativeInner/OrderHistoryPage/orderHistoryPageMb.module.scss
src/simi/App/nativeInner/ProductFullDetail/productFullDetail.module.css
src/simi/App/nativeInner/ProductFullDetail/productFullDetail.scss
src/simi/App/nativeInner/ProductFullDetail/statusBar.scss
src/tokens.module.css

update button color

---

src/simi/App/nativeInner/CategoryList/CategoryDescription/categoryDescription.scss
src/simi/App/nativeInner/Products/index.js
src/simi/App/nativeInner/Products/products.scss
src/simi/App/nativeInner/RootComponents/Category/category.js
src/simi/App/nativeInner/RootComponents/Category/category.scss
src/simi/App/nativeInner/RootComponents/Category/categoryHeader.js
template.html

Update products listing

---

src/simi/App/nativeInner/Cart/PriceAdjustments/ShippingMethods/shippingForm.js
src/simi/App/nativeInner/Cart/PriceAdjustments/ShippingMethods/shippingMethods.js
src/simi/App/nativeInner/Cart/cartPage.js

fix check if else cart and fix button color

---

src/override/button.module.css
src/simi/App/nativeInner/AccountInformationPage/accountInformationPage.module.css
src/simi/App/nativeInner/AccountSubcriptionPage/accountSubcriptionPage.module.css
src/simi/App/nativeInner/Dialog/dialog.module.css
src/simi/App/nativeInner/FooterNative/footerNative.js
src/simi/App/nativeInner/Header/Component/SearchForm.js
src/simi/App/nativeInner/Header/header.js
src/simi/App/nativeInner/Header/header.module.css
src/simi/App/nativeInner/MyAccountPage/myAccountPage.module.css
src/simi/App/nativeInner/OrderDetailPage/orderDetailPage.module.scss
src/simi/App/nativeInner/ProductFullDetail/ProductReview/productreview.module.css

update button size, color header , color icon header

---

src/simi/App/core/AccountInformationPage/accountInformationPage.module.css
src/simi/App/core/AddressBookPage/addressBookPage.module.css
src/simi/App/core/Header/Component/SearchForm.js
src/simi/App/core/Header/cartCounter.module.css
src/simi/App/core/Header/header.module.css
src/simi/App/core/LeftMenu/leftMenu.module.css
src/simi/App/core/Main/main.js
src/simi/App/core/OrderDetailPage/orderDetailPage.module.scss
src/simi/App/core/OrderHistoryPage/orderHistoryPage.module.css
src/simi/App/core/OrderHistoryPage/orderHistoryPageMb.module.scss
src/simi/App/core/OrderHistoryPage/orderRow.module.css
src/simi/App/core/ProductFullDetail/ProductReview/productreview.module.css
src/simi/App/core/ProductFullDetail/productFullDetail.js
src/simi/App/core/ProductFullDetail/productFullDetail.module.css
src/simi/App/core/ProductFullDetail/productFullDetail.scss
src/simi/app.js

update color on 12.0/develop

---

src/simi/App/core/Cart/PriceAdjustments/CouponCode/couponCode.module.css
src/simi/App/core/Cart/PriceAdjustments/priceAdjustments.module.css
src/simi/App/core/Cart/PriceSummary/priceSummary.js
src/simi/App/core/Cart/PriceSummary/priceSummary.module.css
src/simi/App/core/Cart/ProductListing/product.js
src/simi/App/core/Cart/ProductListing/product.module.css
src/simi/App/core/Cart/ProductListing/productListing.module.css
src/simi/App/core/Cart/ProductListing/productListingTableActions.scss
src/simi/App/core/Cart/ProductListing/quantity.module.css
src/simi/App/core/MiniCart/ProductList/item.js
src/simi/App/core/MiniCart/ProductList/item.module.css
src/simi/App/core/MiniCart/miniCart.js
src/simi/App/core/MiniCart/miniCart.module.css
src/simi/App/core/ProductReviewPage/ReviewItems/reviewItem.js
src/simi/App/core/ProductReviewPage/ReviewItems/reviewItem.module.css
src/simi/App/core/WishlistPage/wishlistItem.js
src/simi/App/core/WishlistPage/wishlistItem.module.css
src/simi/BaseComponents/GridItem/Price/price.scss

Update price color, button color for mini cart, products list

---

src/simi/App/core/Cart/cartPage.module.css
src/simi/App/core/ProductFullDetail/productFullDetail.scss
src/simi/App/core/RootComponents/Category/category.js
src/simi/App/core/RootComponents/Category/category.module.css

update background color on checkout , listing , detail

---

src/simi/App/nativeInner/FooterNative/footerNative.js
src/simi/App/nativeInner/Header/Component/SearchForm.js
src/simi/App/nativeInner/Header/Component/search.scss
src/simi/App/nativeInner/Header/header.js
src/simi/App/nativeInner/Header/header.module.css

add padding for app native on header & bottom menu

---

src/simi/App/nativeInner/ProductFullDetail/productFullDetail.js
src/simi/App/nativeInner/Products/index.js

Update related product, category desription

---

src/simi/App/nativeInner/Cart/CouponCode/couponCode.module.css
src/simi/App/nativeInner/Cart/PriceAdjustments/priceAdjustments.js
src/simi/App/nativeInner/Cart/PriceAdjustments/priceAdjustments.module.css
src/simi/App/nativeInner/Cart/PriceSummary/priceSummary.module.css
src/simi/App/nativeInner/Cart/RectButton/RectButton.js
src/simi/App/nativeInner/Cart/RectButton/RectButton.module.css
src/simi/App/nativeInner/Cart/cartPage.module.css

update cart button

---

src/simi/App/core/Cart/PriceAdjustments/ShippingMethods/shippingMethods.module.css
src/simi/App/core/Cart/ProductListing/quantity.module.css
src/simi/App/core/CategoryDescription/categoryDescription.js
src/simi/App/core/CategoryDescription/categoryDescription.scss
src/simi/App/core/CategoryDescription/index.js
src/simi/App/core/MiniCart/ProductList/item.module.css
src/simi/App/core/MiniCart/miniCart.module.css
src/simi/BaseComponents/Products/index.js
src/simi/queries/catalog_gql/catalogFragment.gql.js

Update button color for mini cart, add cms block

---

src/simi/App/nativeInner/AddressBookPage/addEditDialog.js
src/simi/App/nativeInner/AddressBookPage/addressBookPage.js
src/simi/App/nativeInner/Dialog/dialog.js
src/simi/App/nativeInner/Header/header.js
src/simi/App/nativeInner/OrderDetailPage/orderDetailPage.js
src/simi/App/nativeInner/ProductFullDetail/AlertMessages/alertMessages.js
src/simi/App/nativeInner/ProductFullDetail/AlertMessages/styles.scss
src/simi/App/nativeInner/ProductFullDetail/ProductReview/index.js
src/simi/App/nativeInner/ProductFullDetail/SizeChart/index.js
src/simi/App/nativeInner/ProductFullDetail/footerFixedBtn.js
src/simi/App/nativeInner/ProductFullDetail/productFullDetail.js
src/simi/App/nativeInner/ProductFullDetail/statusBar.scss
src/simi/App/nativeInner/ProductImageCarousel/ImageLightbox.scss
src/simi/App/nativeInner/ProductImageCarousel/carousel.js
src/simi/App/nativeInner/Products/index.js

update header & footer, fix bug ui on native

---

src/simi/App/core/Cart/ProductListing/product.js
src/simi/App/core/Cart/ProductListing/productListingFragments.gql.js
src/simi/App/core/MiniCart/ProductList/item.js
src/simi/App/core/MiniCart/ProductList/productListFragments.gql.js
src/simi/talons/ProductFullDetail/productListingFragment.gql.js

Add tax to cart items

---

src/override/routesNative.js
src/simi/App/nativeInner/Header/Component/SearchForm.js
src/simi/App/nativeInner/Header/Component/search.scss
src/simi/App/nativeInner/MyAccountPage/myAccountPage.js
src/simi/App/nativeInner/ProductFullDetail/productFullDetail.js

fixbug loading, header & add clean caches

---

src/simi/App/nativeInner/OrderHistoryPage/orderHistoryPageMb.js
src/simi/App/nativeInner/ProductFullDetail/statusBar.scss

update status bar on detail

---

src/simi/App/nativeInner/Products/NoProductsFound/noProductsFound.module.css

Update no products found

---

src/simi/App/nativeInner/Products/NoProductsFound/noProductsFound.module.css

Update img no products found

---

src/simi/App/nativeInner/Checkout/DeliveryDateTime/style.scss
src/simi/App/nativeInner/Checkout/PaymentInformation/paymentInformation.js
src/simi/App/nativeInner/Checkout/PaymentInformation/paymentInformation.module.css
src/simi/App/nativeInner/Checkout/ShippingInformation/shippingInformation.js
src/simi/App/nativeInner/Checkout/ShippingInformation/shippingInformation.module.css
src/simi/App/nativeInner/Checkout/checkoutPage.js
src/simi/App/nativeInner/Checkout/checkoutPage.module.css

12.0/native inner/feature/checkout

---

src/simi/App/nativeInner/CategoryList/CategoryDescription/categoryDescription.scss
src/simi/App/nativeInner/Products/index.js
src/simi/App/nativeInner/WishlistPage/wishlistItem.js
src/simi/App/nativeInner/WishlistPage/wishlistItem.module.css
src/simi/BaseComponents/SocialShare/index.js

12.0/native inner/fixbug duy

---

src/simi/App/nativeInner/Cart/CartProduct/CartProduct.js
src/simi/App/nativeInner/Cart/ProductListingWithBrandSeparation/ProductListingWithBrandSeparation.module.css
src/simi/App/nativeInner/CategoryList/CategoryDescription/categoryDescription.js
src/simi/App/nativeInner/CategoryList/CategoryDescription/categoryDescription.scss
src/simi/App/nativeInner/CategoryList/productsList.module.css
src/simi/App/nativeInner/Products/NoProductsFound/noProductsFound.js
src/simi/App/nativeInner/Products/NoProductsFound/noProductsFound.module.css
src/simi/App/nativeInner/Products/index.js
src/simi/App/nativeInner/RootComponents/Search/search.js
src/simi/queries/catalog_gql/category.gql.js

12.0/native inner/duy fixbug

---

src/simi/App/nativeInner/Header/header.js
src/simi/App/nativeInner/NoMatch/index.js
src/simi/App/nativeInner/OrderDetailPage/orderDetailPage.gql.js
src/simi/App/nativeInner/OrderDetailPage/orderDetailPage.js
src/simi/App/nativeInner/OrderDetailPage/orderDetailPage.module.scss

fixbug order detail
